config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  resources :users do
    member do
      get 'profile'
      get 'matches'
    end
  end
  
  #Omniauth sign in and out 
  #session create action we'll add a facebook callback route
  get 'auth/:provider/callback', to: 'sessions#create'
  #For the session destroy action we'll add a regular delete request to the sessions destroy action.
  match 'sign_out', to: 'sessions#destroy', via: :delete  

  # 
  post 'create_friendship' => "friendships#create"
  delete 'delete_friendship' => "friendships#destroy"
  
  get 'matches/get_email' => "users#get_email"

  
end

app/models/user.rb
class User < ActiveRecord::Base
    
    # jtinder slide sort order 
    default_scope { order('id DESC') }    

    # create association with users having friends
	  has_many :friendships, dependent: :destroy
    has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy
    
    # for paperclip gem
	  has_attached_file :avatar,
					  :storage => :s3,
					  :style => { :medium => "370x370", :thumb => "100x100" }
    
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    
    # ----begin omniauth
    # "sign_in_from_omniauth(auth)" from sessions_controller.rb calls directly on the User class
	  def self.sign_in_from_omniauth(auth)
		  find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
	  end
    
    # creates a new user with the fields passed in by the auth hash.
	  def self.create_user_from_omniauth(auth)
        create(
                
    		avatar: process_uri(auth['info']['image'] + "?width=9999"),
    		email: auth['info']['email'],
    		provider: auth['provider'],
    		uid: auth['uid'],
    		name: auth['info']['name'],
    		gender: auth['extra']['raw_info']['gender'],
    		date_of_birth: auth['extra']['raw_info']['birthday'],
    		location: auth['info']['location'],
    		bio: auth['extra']['raw_info']['bio']
		)
	  end
    # ----end omniauth

    # Begin Friendship Match Methods
    # first user/self requests match with user 2
    def request_match(user2)
        self.friendships.create(friend: user2)
    end
    
    # first user/self accepts match with user 2
    def accept_match(user2)
        self.friendships.where(friend: user2).first.update_attribute(:state, "ACTIVE")
    end
    
    #
	  def remove_match(user2)
      inverse_friendship = inverse_friendships.where(user_id: user2).first
      if inverse_friendship
          self.inverse_friendships.where(user_id: user2).first.destroy
      else
          self.friendships.where(friend_id: user2).first.destroy
      end
    end    
    
    # End Friendship Match Methods

    def accept_friendship
		  self.update_attributes(state: "active", friended_at: Time.now)
	  end

    # Begin Query Methods
    
    # include results by user selected interest
    def self.gender(user)
      case user.interest
        when "Male"
          where('gender = ?', 'male')
        when "Female"
          where('gender = ?', 'female')
        else
          all
      end
    end        
  
    #Exclude the current user
    def self.not_me(current_user)
       where.not(id: current_user.id) 
    end

    # End Query Methods
    
    def matches(current_user)
      friendships.where(state: "pending").map(&:friend) + current_user.friendships.where(state: "ACTIVE").map(&:friend) + current_user.inverse_friendships.where(state: "ACTIVE").map(&:user) 
    end
  
    #/ Filter methods \#

    private

    #parses the uri with an https scheme.
    def self.process_uri(uri)
        image_url = URI.parse(uri)
        image_url.scheme = 'https'
        image_url.to_s
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
	
	#set user before allowing access to user settings
	before_action :set_user, only:[:edit, :profile, :update, :destroy, :get_email, :matches]
	
  # old fetching all the users and assign them to the @users instance variable.... removed @users = User.all
  # 
	def index
	  # getting the users, on the index action, according with the url params sent via the Plugin. 
	  # using javascript response in index.js.erb under the views/users folder.
    # filter to display results by gender. see models/user.rb => def self.gender(user)
    # filter to exclude current user from list. add not_me => see models/user.rb => def self.not_me(current_user)
    if params[:id]
      @users = User.gender(current_user).where('id < ?', params[:id]).not_me(current_user).limit(10) - current_user.matches(current_user)
    else
      @users = User.gender(current_user).not_me(current_user).limit(10) - current_user.matches(current_user)
    end

    # 
    respond_to do |format|
      format.html
      format.js
    end
  end	  
	
	def edit
	   authorize! :update, @user
	end

  def update
    if @user.update(user_params)
      respond_to do |format|
        format.html { redirect_to users_path}
      end
    else
      redirect_to edit_user_path(@user)
    end
  end
	
  def destroy
    if @user.destroy
      session[:user_id] = nil
      session[:omniauth] = nil
      redirect_to root_path
    else
      redirect_to edit_user_path(@user)
    end
  end
    
  def profile
  end
  
  #variable @matches joins all the ACTIVE friendships and inverse_friendships that the user has which will give the collection of matches they have.
  def matches
    authorize! :read, @user
    @matches = current_user.friendships.where(state: "ACTIVE").map(&:friend) + current_user.inverse_friendships.where(state: "ACTIVE").map(&:user)
  end

  def get_email
    respond_to do |format|
      format.js 
    end
  end

	private
  
  #find the user to edit 
	def set_user
		@user = User.find(params[:id])
	end
  
  #set params for user settings to be edited in update
	def user_params
		params.require(:user).permit(:interest, :bio, :avatar, :location, :date_of_birth)
	end  
  
end

app/helpers/users_helper.rb
module UsersHelper
    
    def name(user)
		if user.name
			case user
				when user
					user.name.partition(' ').first
				when @user
					@user.name.partition(' ').first
			end
		end
	end
	
	
	def age(user)
	# following user helper converts the birth date into the number of years.
		if user.date_of_birth
			case user
				when user
					age = Date.today.year - user.date_of_birth.year 
		        	age -= 1 if Date.today < user.date_of_birth + age.years
		        	return age
				when @user
					age = Date.today.year - @user.date_of_birth.year 
		        	age -= 1 if Date.today < @user.date_of_birth + age.years
		        	return age
			end
		end
	end

	def location(user)
		if user.location
			case user
			   when user
			   	user.location.partition(',').first
			   when @user
			   	@user.location.partition(',').first
			end
		end
	end

end

app/views/users/_match.html.erb
<tr>
	<!-- image -->
	<th scope="row"><%= image_tag "#{match.avatar.url(:original)}", size: "50x50" %></th>
	
	<!-- name -->
	<td><%= link_to match.name, profile_user_path(match.id) %></td> 
	
	<!-- matched date -->
	<td><%= match.updated_at.strftime('%m/%d/%Y') %></td>
	
	<!-- buttons --> 
	<td class="text-right">
		<%= link_to matches_get_email_path(id: "#{match.id}"), :data => {toggle: "tooltip", placement: "top" }, title: "Get Email", remote: :true  do %>
			<i class="fa fa fa-envelope"></i>
		<% end %>
	
		<%= link_to delete_friendship_path(friend_id: match.id), :data => {toggle: "tooltip", placement: "top", confirm: "Are you sure you want to unmatch with #{match.name} ?" }, title: "Unmatch", id: "delete_friendship", method: :delete do %>
			<i class="fa fa fa-times"></i>
		<% end %>
	</td>
</tr>

app/views/users/_user.html.erb
<!-- Each partial we'll correspond to each Jtinder slide -->
<li id="<%= user.id %>">
    
    <div class="img"><%= image_tag user.avatar.url(:original), width: "100%", heigth: "100%" %></div> 
    
    <div class="user-name pull-left">
    	<%= link_to profile_user_path(user.id) do %>
    	    <b><%= name(user) %></b>, 
    	    <%= age(user) %>
    	<% end %>
    </div>
    
    <div class="user-location text-right"><i class="fa fa-map-marker"></i> <%= location(user) %></div>
    
    <div class="like"></div>
    <div class="dislike"></div>
    
    <%= link_to "", create_friendship_path(friend_id: user.id), id: "user_#{user.id}", method: :post, :remote => true %> 
</li>

app/views/users/edit.html.erb
<%= simple_form_for(@user, url: url_for(:action => 'update', :controller => 'users'), html: {multipart: true} ) do |f| %>

    <div class="container">
        Edit Profile: <%= current_user.name %>
        
        <!-- Intersted in drop down -->
        <h4 class="text-uppercase"><small>Interested in</small></h4>
        <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
              <%= current_user.interest.capitalize %>
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
              <li role="presentation" class="dropdown-header">Interested in</li>
              <li role="presentation" class="gender"><a role="menuitem" tabindex="-1" href="#">Female</a></li>
              <li role="presentation" class="gender"><a role="menuitem" tabindex="-1" href="#">Male</a></li>
              <li role="presentation" class="gender"><a role="menuitem" tabindex="-1" href="#">Both</a></li>
            </ul>
        </div>
        <!-- check this --> 
        <%= f.input :interest, as: :hidden, label: false %>

        <!-- Profile description input box on users "bio" -->
        <h4 class="text-uppercase"><small>Profile Description</small></h4>
        <%= f.input :bio, as: :text, label: false, :input_html => { :rows => 5, class: 'form-control' } %>
        
        <!-- City input box on users "location"-->
        <h4 class="text-uppercase"><small>City</small></h4>
        <%= f.input :location, label: false, :input_html => { :rows => 1, class: 'form-control' } %>
        
        <!-- Age input on users "date_of_birth" --> 
        <h4 class="text-uppercase"><small>Age</small></h4>
        <%= f.input :date_of_birth, as: :string, label: false, :input_html => { :rows => 1, class: 'form-control' } %>
        <br>
        
        <!-- file input on users image -- not working -->        
        <div class="text-center">
          <div class="fileinput fileinput-new" data-provides="fileinput">
              <div class="fileinput-new thumbnail" style="width: 100px; height: 75px;">
                <img data-src="holder.js/100%x100%" src="<%= current_user.avatar %>">
              </div>
              <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 100px; max-height: 75px;"></div>
              <div>
                <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span><%= f.file_field :avatar %></span>
                <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
              </div>
            </div>
        </div>

      <%= f.button :submit, class: "btn btn-primary btn-block btn-xs", value: "Submit" %>
      <br />
      <%= link_to 'Cancel your account', user_path(current_user.id), :method => :delete, data: { confirm: 'Are you sure you want to delete your account?' }, title: "Delete Account"  %>
    </div>

<% end %>

<script type="text/javascript">
	$('.gender').click(function(){
		$("#dropdownMenu1").text( $(this).text() );
		$("#dropdownMenu1").append('<span class="caret"></span>');
		$("#user_interest").val( $(this).text() );
	});
</script>

app/views/users/get_email.js.erb
swal("Email", "<%= @user.email %>");

app/views/users/index.html.erb
<div class="container">

    <br>

    <!-- START JTINDER -->
    <div class="row">
       <div class="text-center">
        <!-- start padding container -->
        <div class="wrap">
            <!-- start jtinder container -->
            <div id="tinderslide">
                <ul>
                    <%= render @users %>
                </ul>
            </div>
            <!-- end jtinder container -->
        </div>
        <!-- end padding container -->
       </div>
    </div>

        <!-- jTinder trigger by buttons  -->
        <div class="actions">
            <a href="#" class="dislike"><i class="fa fa-times"></i></a>
            <a href="#" class="like"><i class="fa fa-heart"></i></a>
        </div>

    <!-- END JTINDER -->

</div>


<div class="spinner center_spinner">
  <div class="rect1"></div>
  <div class="rect2"></div>
  <div class="rect3"></div>
  <div class="rect4"></div>
  <div class="rect5"></div>
</div>

app/views/users/index.js.erb
$( "#tinderslide ul" ).append('<%= escape_javascript(render(:partial => @users, :collection => @users)) %>');
$("#tinderslide > ul li").tsort({attr:"id"});
$("#tinderslide").jTinder();
load_more = true;

app/views/users/matches.html.erb
<div class="container">
    <table class="table table-striped">
		<!-- heading --> 
		<thead>
			<tr>
				<th></th>
				<th>Name</th>
				<th>Matched on</th>
				<th></th>
			</tr>
		</thead>
	<tbody>
	    <!-- match rows --> 
		<%= render partial: "match", collection: @matches %>
	</tbody>
    </table>
</div>

<script type="text/javascript">
	$(function () {
		$('[data-toggle="tooltip"]').tooltip();
	});
</script>

app/views/users/profile.html.erb
  <div class="container">
      <div class="wrap">
          <div class="profile-box">
              <div class="img">
                 <%= image_tag @user.avatar.url(:original), width: "100%", heigth: "100%"  %>
             </div>
             <div class="user-name pull-left"><a href=""><b><%= name(@user) %></b>, <%= age(@user) %></a></div>
             <div class="user-location text-right"><i class="fa fa-map-marker"></i> <%= @user.location %></div>
             <div class="description">
                 <h4 class="text-uppercase"><small>Description</small></h4>
                 <p class="small"><%= @user.bio %></p>
             </div>
         </div>
     </div>
  </div>