config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  resources :users do
    member do
      get 'profile'
      get 'matches'
    end
  end
  
  #Omniauth sign in and out 
  #session create action we'll add a facebook callback route
  get 'auth/:provider/callback', to: 'sessions#create'
  #For the session destroy action we'll add a regular delete request to the sessions destroy action.
  match 'sign_out', to: 'sessions#destroy', via: :delete  

  # 
  post 'create_friendship' => "friendships#create"
  delete 'delete_friendship' => "friendships#destroy"
  
  get 'matches/get_email' => "users#get_email"

  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tinderish</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=0.9">
</head>
<body>

<% if current_user %>
	<nav id="myNavmenu" class="navmenu navmenu-default navmenu-fixed-left offcanvas" role="navigation">
		<ul class="nav navmenu-nav">
		
			<li class="<%= if params[:action] == "index" then "active" end %> nav-btn">
				<%= link_to root_path do %><i class="fa fa-users"></i> Discover <% end %>
			</li>

			<li class="<%= if params[:action] == "matches" then "active" end %> nav-btn">
				<%= link_to matches_user_path(current_user) do %><i class="fa fa-heart"></i> Matches <% end %>
			</li>

			<li class="<%= if params[:action] == "edit" then "active" end %> nav-btn">
				<%= link_to edit_user_path(current_user) do %><i class="fa fa-cog"></i> Settings <% end %>
			</li>

			<li class="nav-btn"><%= link_to '/sign_out', method: :delete do %><i class="fa fa-cog"></i> Log out <% end %></li>

		</ul>
	</nav>

	<div class="navbar navbar-default navbar-fixed-top">
	  
		  <button type="button" class="navbar-toggle button-nav" data-toggle="offcanvas" data-target="#myNavmenu" data-canvas="body">
		  	<i class="fa fa-cog"></i>
		  </button>

		  <%= link_to root_path, class: "navbar-brand" do %>
		  	<%= image_tag "logo.png", alt: "logo", class: "logo-brand" %>
		  <% end %>

		  <button type="button" class="navbar-toggle button-nav pull-right">
		  	<%= link_to matches_user_path(current_user) do %><i class="fa fa-heart"></i><% end %>
		  </button>

	</div>

<% else %>

	<a class="navbar-brand" href="#">
			<%= image_tag "logo_white.png", alt: "Logo", class: "logo-brand" %>
	</a>
	
<% end %>

<%= yield %>


	<script type="text/javascript">
	
		// Allow to load more
		var load_more = true;
		// Hide Spinner
		$(".spinner").hide();
		// Tooltip
		$('[data-toggle="tooltip"]').tooltip();
		
		
		/** Set button action to trigger jTinder like & dislike. */
		$('.actions .like, .actions .dislike').click(function(e){
			e.preventDefault();
			$("#tinderslide").jTinder($(this).attr('class'));
		});
		
		//* initialize the sort function by sorting the Tinderslide  li  elements by ID ... using 2 files in vendors js tinysort *//
		$("#tinderslide > ul li").tsort({attr:"id"});
		
		
		//* add the initialization script with 2 events onDislike onLike *//
		$("#tinderslide").jTinder({
		    onDislike: function (item) {
		        //
		    },
		    
		    //*onlike function basically fetches the last tinderslide element ( the element you're currently liking ) and click it*//
		    onLike: function (item) {
		       var myId = $("#tinderslide > ul li").last().attr("id");
			    $("#user_" + myId)[0].click();
		    },
		    animationRevertSpeed: 200,
		    animationSpeed: 400,
		    threshold: 1,
		    likeSelector: '.like',
		    dislikeSelector: '.dislike'
		});
		
		//* hover effects to the navbar buttons *//
		$(".nav-btn").hover(function(){
			$(this).addClass("active2");
			}, function(){
			$(this).removeClass("active2");	
		});
			
	</script>

</body>
</html>